import { defineStore } from 'pinia';
import type { CartItem, Sale, OrderType, PaymentMethod } from '../types';
import { apiClient } from '../services/api';

export const useSalesStore = defineStore('sales', {
  state: () => ({
    currentCart: [] as CartItem[],
    currentOrderType: 'DINE_IN' as OrderType,
    currentCustomerName: '',
    dailySales: [] as Sale[],
    taxPercent: 0,
    discountAmount: 0, // Fixed discount amount in IDR
    isLoading: false,
    error: null as string | null,
  }),

  getters: {
    subtotal: (state) =>
      state.currentCart.reduce((sum, item) => {
        const variantExtra = item.selectedVariantIds.reduce((acc, variantId) => {
          const variant = item.product.variants?.find((v) => v.id === variantId);
          return acc + (variant?.extraPrice || 0);
        }, 0);
        return sum + (item.product.basePrice + variantExtra) * item.qty;
      }, 0),
    taxAmount(): number {
      return ((this.subtotal - this.discountAmount) * this.taxPercent) / 100;
    },
    total(): number {
      return this.subtotal - this.discountAmount + this.taxAmount;
    },
  },

  actions: {
    async loadFromStorage() {
      // Data transaksi kini murni dibaca dari Backend API,
      // kita hilangkan pembacaan kotor dari localStorage.
      await this.loadSalesReport();
    },

    async loadSalesReport(startDate?: string, endDate?: string) {
      this.isLoading = true;
      this.error = null;
      try {
        const result = await apiClient.getSalesReport(startDate, endDate);
        if ((result as any).error) {
          this.error = (result as any).error;
          return;
        }
        // Ensure sales are sorted by date
        const sortedSales = ((result.data?.sales || []) as Sale[]).sort(
          (a, b) => new Date(b.date).getTime() - new Date(a.date).getTime()
        );
        this.dailySales = sortedSales;
      } catch (error: any) {
        this.error = error.message;
      } finally {
        this.isLoading = false;
      }
    },

    addToCart(item: CartItem) {
      this.currentCart.push(item);
    },

    clearCart() {
      this.currentCart = [];
      this.currentCustomerName = '';
      this.currentOrderType = 'DINE_IN';
    },

    removeFromCart(index: number) {
      this.currentCart.splice(index, 1);
    },

    updateCartItem(index: number, qty: number) {
      if (qty <= 0) {
        this.removeFromCart(index);
      } else {
        this.currentCart[index].qty = qty;
      }
    },

    setDiscount(amount: number) {
      this.discountAmount = Math.max(0, Math.min(amount, this.subtotal));
    },

    setTax(percent: number) {
      this.taxPercent = Math.max(0, Math.min(percent, 100));
    },

    async finalizeSale(method: PaymentMethod, paidAmount: number) {
      this.isLoading = true;
      this.error = null;
      try {
        const saleData = {
          customerName: this.currentCustomerName,
          orderType: this.currentOrderType,
          items: this.currentCart, // Send the full items so API stores complete data
          subtotal: this.subtotal,
          discount: this.discountAmount,
          tax: this.taxAmount,
          total: this.total,
          paymentMethod: method,
          paidAmount,
        };

        const result = await apiClient.createSale(saleData);

        if ((result as any).error) {
          throw new Error((result as any).error);
        }

        // orderNumber is now generated by the backend. We will just use what backend returns.
        const returnedSale = result.data?.sale;
        
        if (!returnedSale) {
          throw new Error('Failed to retrieve sale data from server');
        }
        
        // Create proper Sale object with complete structure from backend response
        const sale: Sale = {
          id: returnedSale.id,
          orderNumber: returnedSale.orderNumber,
          date: returnedSale.date || new Date().toISOString(),
          customerName: this.currentCustomerName || returnedSale.customerName,
          orderType: this.currentOrderType,
          items: this.currentCart,
          subtotal: this.subtotal,
          discount: this.discountAmount,
          tax: this.taxAmount,
          total: this.total,
          payment: {
            method,
            paidAmount,
            change: paidAmount - this.total,
          },
          status: 'COMPLETED',  // ✅ Transaction is complete after payment
        };
        
        // Save the updated sale object with orderNumber and status back via API or update local array
        // Update array secara reaktif
        this.dailySales.unshift(sale);

        // Notify other tabs (e.g. Barista)
        try {
          const bc = new BroadcastChannel('pos-sales-updates');
          bc.postMessage({ type: 'NEW_SALE', saleId: sale.id });
          bc.close();
        } catch (e) {
          console.warn('BroadcastChannel not supported');
        }

        this.clearCart();
        this.discountAmount = 0;
        this.taxPercent = 0;

        return {
          success: true,
          sale,
          change: paidAmount - this.total,
        };
      } catch (error: any) {
        this.error = error.message;
        return { success: false, error: error.message };
      } finally {
        this.isLoading = false;
      }
    },
    
    // Add method to update order status
    async updateOrderStatus(saleId: string, newStatus: string) {
      try {
        await apiClient.updateSaleStatus(saleId, newStatus);
        const saleIndex = this.dailySales.findIndex(s => s.id === saleId);
        if (saleIndex !== -1) {
          this.dailySales[saleIndex].status = newStatus as any;
          
          try {
            const bc = new BroadcastChannel('pos-sales-updates');
            bc.postMessage({ type: 'STATUS_UPDATE', saleId, status: newStatus });
            bc.close();
          } catch (e) {}
        }
      } catch (error) {
        console.error('Failed to update status', error);
      }
    }
  },
});